import { useCallback, useEffect, useState } from "react";
import { clearSession, readSession, request, signIn } from "./api";

const error = (value) => window.alert(value.message || "No se pudo completar la solicitud.");
const date = (value) => value ? new Date(value).toLocaleString("es-UY") : "-";

function Login({ onLogin }) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState("");
  const submit = async (event) => { event.preventDefault(); try { onLogin(await signIn(email, password)); } catch (value) { setMessage(value.message); } };
  return <main className="login"><form onSubmit={submit}><h1>Fermil Platform</h1><p>Consola exclusiva de superadministracion.</p>{message && <div className="error">{message}</div>}<input type="email" placeholder="Correo" value={email} onChange={(event) => setEmail(event.target.value)} required /><input type="password" placeholder="Contrasena" value={password} onChange={(event) => setPassword(event.target.value)} required /><button>Ingresar</button></form></main>;
}

function Console({ onLogout }) {
  const [organizations, setOrganizations] = useState([]); const [users, setUsers] = useState([]); const [audit, setAudit] = useState([]); const [form, setForm] = useState({ name: "", taxId: "", planCode: "basic", adminName: "", adminEmail: "", adminPassword: "" });
  const load = useCallback(async () => { try { const [orgs, userList, logs] = await Promise.all([request("/api/platform/organizations"), request("/api/platform/users?limit=100"), request("/api/platform/audit?limit=30")]); setOrganizations(orgs); setUsers(userList.data); setAudit(logs); } catch (value) { error(value); } }, []);
  useEffect(() => { load(); }, [load]);
  const createOrganization = async (event) => { event.preventDefault(); try { await request("/api/platform/organizations", { method: "POST", body: { name: form.name, taxId: form.taxId || null, planCode: form.planCode, initialAdmin: { fullName: form.adminName, email: form.adminEmail, password: form.adminPassword } } }); setForm({ name: "", taxId: "", planCode: "basic", adminName: "", adminEmail: "", adminPassword: "" }); load(); } catch (value) { error(value); } };
  const toggleOrganization = async (organization) => { try { await request(`/api/platform/organizations/${organization.id}/${organization.status === "active" ? "suspend" : "reactivate"}`, { method: "POST", body: {} }); load(); } catch (value) { error(value); } };
  return <main className="console"><header><div><strong>FERMIL PLATFORM</strong><span>Administracion global</span></div><button className="secondary" onClick={onLogout}>Cerrar sesion</button></header><section><div className="section-title"><h1>Organizaciones</h1><button className="secondary" onClick={load}>Actualizar</button></div><div className="grid"><form className="panel" onSubmit={createOrganization}><h2>Nueva organizacion</h2><input placeholder="Nombre *" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required /><input placeholder="RUT / Tax ID" value={form.taxId} onChange={(event) => setForm({ ...form, taxId: event.target.value })} /><select value={form.planCode} onChange={(event) => setForm({ ...form, planCode: event.target.value })}><option value="basic">Basic</option><option value="professional">Professional</option><option value="enterprise">Enterprise</option></select><hr /><input placeholder="Nombre del admin inicial *" value={form.adminName} onChange={(event) => setForm({ ...form, adminName: event.target.value })} required /><input type="email" placeholder="Email del admin *" value={form.adminEmail} onChange={(event) => setForm({ ...form, adminEmail: event.target.value })} required /><input type="password" placeholder="Contrasena (minimo 12) *" value={form.adminPassword} onChange={(event) => setForm({ ...form, adminPassword: event.target.value })} minLength="12" required /><button>Crear organizacion</button></form><div className="panel list">{organizations.map((org) => <div className="row" key={org.id}><div><strong>{org.name}</strong><small>{org.planCode} · {org.status}</small></div><button className={org.status === "active" ? "danger" : ""} onClick={() => toggleOrganization(org)}>{org.status === "active" ? "Suspender" : "Reactivar"}</button></div>)}</div></div></section><section><div className="section-title"><h1>Usuarios globales</h1><span>{users.length} cargados</span></div><div className="panel table"><table><thead><tr><th>Usuario</th><th>Organizacion</th><th>Roles</th><th>Estado</th></tr></thead><tbody>{users.map((user) => <tr key={user.id}><td><strong>{user.fullName}</strong><br /><small>{user.email}</small></td><td>{user.isPlatformAdmin ? "Plataforma" : user.organization?.name || "-"}</td><td>{user.roles.map((role) => role.name).join(", ") || "-"}</td><td>{user.status}</td></tr>)}</tbody></table></div></section><section><h1>Auditoria de plataforma</h1><div className="panel list">{audit.map((entry) => <div className="row" key={entry.id}><div><strong>{entry.action}</strong><small>{entry.actor?.fullName || "Sistema"} · {date(entry.createdAt)}</small></div></div>)}</div></section></main>;
}

export default function App() { const [user, setUser] = useState(readSession()?.user || null); if (!user) return <Login onLogin={setUser} />; return <Console onLogout={() => { clearSession(); setUser(null); }} />; }
